// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MailClient is an autogenerated mock type for the MailClient type
type MailClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: from, tos, subject, body, ccs, bccs
func (_m *MailClient) Send(from string, tos []string, subject string, body string, ccs []string, bccs []string) error {
	ret := _m.Called(from, tos, subject, body, ccs, bccs)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string, string, string, []string, []string) error); ok {
		r0 = rf(from, tos, subject, body, ccs, bccs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
