// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package server

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s: confirm mail address": 0,
	"%s: password reset":       3,
	"Hi %s! Please confirm your mail address by clicking the following link. Thanks!\n%s":                                                                1,
	"Hi %s! To reset your password, click the following link: \n%s\n\nIf you did not request to reset your password, please ignore this message. Thanks": 4,
	"could not find group with id %s":                                  32,
	"could not find user with id %s":                                   47,
	"could not parse given language":                                   49,
	"error while counting groups":                                      34,
	"error while counting users":                                       51,
	"error while looking up groups":                                    37,
	"error while querying member":                                      38,
	"error while saving group":                                         13,
	"error while saving user":                                          28,
	"error while sending mail: %s":                                     2,
	"group name needs to have a length of at least 3":                  33,
	"invalid group id '%s'":                                            12,
	"invalid id '%s'":                                                  9,
	"invalid mail address":                                             50,
	"invalid page token, unable to unmarshal to page token: %s":        45,
	"invalid token":                                                    19,
	"invalid user id":                                                  29,
	"invalid user id '%s'":                                             27,
	"invalid username, only lowercase letters and numbers are allowed": 48,
	"mail address not set":                                             54,
	"mismatch between given filter %s and filter in page token %s":     46,
	"no token given":                                                   17,
	"not allowed to change password for other users":                   63,
	"not allowed to create groups":                                     39,
	"not allowed to delete groups":                                     43,
	"not allowed to delete user":                                       61,
	"not allowed to edit other users":                                  57,
	"not allowed to set confirmed":                                     55,
	"not allowed to update groups":                                     40,
	"only %v of %v given memberIds were found":                         36,
	"password cannot be changed using the UpdateUser function, use ChangePassword instead": 59,
	"password mismatch":                                              64,
	"password must have a length of at least 7":                      52,
	"roles cannot be assigned to users directly":                     58,
	"roles cannot be assigned to users directly, use groups instead": 53,
	"the request was canceled by the client":                         5,
	"token mismatch":                                                 18,
	"unable to count groups: %s":                                     6,
	"unable to count users: %s":                                      22,
	"unable to create generate field mask: %s":                       41,
	"unable to create page token: %s":                                31,
	"unable to decode group: %s":                                     8,
	"unable to decode user: %s":                                      24,
	"unable to encrypt confirmation":                                 16,
	"unable to encrypt reset password struct":                        21,
	"unable to find group named %s":                                  11,
	"unable to find group with id %s":                                10,
	"unable to find group with id '%s'":                              14,
	"unable to find user":                                            26,
	"unable to find user with given id":                              30,
	"unable to find user with id %s":                                 25,
	"unable to hash given password":                                  56,
	"unable to json marshal confirmation":                            15,
	"unable to json marshal reset password struct":                   20,
	"unable to marshal token to json: %s":                            44,
	"unable to merge groups":                                         42,
	"unable to merge users":                                          60,
	"unable to query groups: %s":                                     7,
	"unable to query members":                                        35,
	"unable to query users: %s":                                      23,
	"unable to remove user from group %s":                            62,
	"unable to save user":                                            65,
	"unable to send reset password mail":                             66,
}

var deIndex = []uint32{ // 68 elements
	// Entry 0 - 1F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 20 - 3F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	// Entry 40 - 5F
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
} // Size: 296 bytes

const deData string = ""

var enIndex = []uint32{ // 68 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001c, 0x00000075, 0x00000095,
	0x000000ab, 0x00000141, 0x00000168, 0x00000186,
	0x000001a4, 0x000001c2, 0x000001d5, 0x000001f8,
	0x00000219, 0x00000232, 0x0000024b, 0x00000270,
	0x00000294, 0x000002b3, 0x000002c2, 0x000002d1,
	0x000002df, 0x0000030c, 0x00000334, 0x00000351,
	0x0000036e, 0x0000038b, 0x000003ad, 0x000003c1,
	0x000003d9, 0x000003f1, 0x00000401, 0x00000423,
	// Entry 20 - 3F
	0x00000446, 0x00000469, 0x00000499, 0x000004b5,
	0x000004cd, 0x000004fc, 0x0000051a, 0x00000536,
	0x00000553, 0x00000570, 0x0000059c, 0x000005b3,
	0x000005d0, 0x000005f7, 0x00000634, 0x00000677,
	0x00000699, 0x000006da, 0x000006f9, 0x0000070e,
	0x00000729, 0x00000753, 0x00000792, 0x000007a7,
	0x000007c4, 0x000007e2, 0x00000802, 0x0000082d,
	0x00000882, 0x00000898, 0x000008b3, 0x000008da,
	// Entry 40 - 5F
	0x00000909, 0x0000091b, 0x0000092f, 0x00000952,
} // Size: 296 bytes

const enData string = "" + // Size: 2386 bytes
	"\x02%[1]s: confirm mail address\x02Hi %[1]s! Please confirm your mail ad" +
	"dress by clicking the following link. Thanks!\x0a%[2]s\x02error while se" +
	"nding mail: %[1]s\x02%[1]s: password reset\x02Hi %[1]s! To reset your pa" +
	"ssword, click the following link: \x0a%[2]s\x0a\x0aIf you did not reques" +
	"t to reset your password, please ignore this message. Thanks\x02the requ" +
	"est was canceled by the client\x02unable to count groups: %[1]s\x02unabl" +
	"e to query groups: %[1]s\x02unable to decode group: %[1]s\x02invalid id " +
	"'%[1]s'\x02unable to find group with id %[1]s\x02unable to find group na" +
	"med %[1]s\x02invalid group id '%[1]s'\x02error while saving group\x02una" +
	"ble to find group with id '%[1]s'\x02unable to json marshal confirmation" +
	"\x02unable to encrypt confirmation\x02no token given\x02token mismatch" +
	"\x02invalid token\x02unable to json marshal reset password struct\x02una" +
	"ble to encrypt reset password struct\x02unable to count users: %[1]s\x02" +
	"unable to query users: %[1]s\x02unable to decode user: %[1]s\x02unable t" +
	"o find user with id %[1]s\x02unable to find user\x02invalid user id '%[1" +
	"]s'\x02error while saving user\x02invalid user id\x02unable to find user" +
	" with given id\x02unable to create page token: %[1]s\x02could not find g" +
	"roup with id %[1]s\x02group name needs to have a length of at least 3" +
	"\x02error while counting groups\x02unable to query members\x02only %[1]v" +
	" of %[2]v given memberIds were found\x02error while looking up groups" +
	"\x02error while querying member\x02not allowed to create groups\x02not a" +
	"llowed to update groups\x02unable to create generate field mask: %[1]s" +
	"\x02unable to merge groups\x02not allowed to delete groups\x02unable to " +
	"marshal token to json: %[1]s\x02invalid page token, unable to unmarshal " +
	"to page token: %[1]s\x02mismatch between given filter %[1]s and filter i" +
	"n page token %[2]s\x02could not find user with id %[1]s\x02invalid usern" +
	"ame, only lowercase letters and numbers are allowed\x02could not parse g" +
	"iven language\x02invalid mail address\x02error while counting users\x02p" +
	"assword must have a length of at least 7\x02roles cannot be assigned to " +
	"users directly, use groups instead\x02mail address not set\x02not allowe" +
	"d to set confirmed\x02unable to hash given password\x02not allowed to ed" +
	"it other users\x02roles cannot be assigned to users directly\x02password" +
	" cannot be changed using the UpdateUser function, use ChangePassword ins" +
	"tead\x02unable to merge users\x02not allowed to delete user\x02unable to" +
	" remove user from group %[1]s\x02not allowed to change password for othe" +
	"r users\x02password mismatch\x02unable to save user\x02unable to send re" +
	"set password mail"

	// Total table size 2978 bytes (2KiB); checksum: BB449CA5
