// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s: confirm mail address": 0,
	"%s: password reset":       3,
	"Hi %s! Please confirm your mail address by clicking the following link. Thanks!\n%s":                                                                1,
	"Hi %s! To reset your password, click the following link: \n%s\n\nIf you did not request to reset your password, please ignore this message. Thanks": 4,
	"could not find group with id %s":                                  6,
	"could not find user with id %s":                                   21,
	"could not parse given language":                                   23,
	"error while counting groups":                                      8,
	"error while counting users":                                       25,
	"error while looking up groups":                                    11,
	"error while querying member":                                      12,
	"error while saving group":                                         51,
	"error while saving user":                                          64,
	"error while sending mail: %s":                                     2,
	"group name needs to have a length of at least 3":                  7,
	"invalid group id '%s'":                                            50,
	"invalid id '%s'":                                                  47,
	"invalid mail address":                                             24,
	"invalid page token, unable to unmarshal to page token: %s":        19,
	"invalid token":                                                    42,
	"invalid user id":                                                  65,
	"invalid user id '%s'":                                             63,
	"invalid username, only lowercase letters and numbers are allowed": 22,
	"mail address not set":                                             28,
	"mismatch between given filter %s and filter in page token %s":     20,
	"no token given":                                                   41,
	"not allowed to change password for other users":                   37,
	"not allowed to create groups":                                     13,
	"not allowed to delete groups":                                     17,
	"not allowed to delete user":                                       35,
	"not allowed to edit other users":                                  31,
	"not allowed to set confirmed":                                     29,
	"not allowed to update groups":                                     14,
	"only %v of %v given memberIds were found":                         10,
	"password cannot be changed using the UpdateUser function, use ChangePassword instead": 33,
	"password mismatch":                                              38,
	"password must have a length of at least 7":                      26,
	"roles cannot be assigned to users directly":                     32,
	"roles cannot be assigned to users directly, use groups instead": 27,
	"the request was canceled by the client":                         43,
	"token mismatch":                                                 55,
	"unable to count groups: %s":                                     44,
	"unable to count users: %s":                                      58,
	"unable to create generate field mask: %s":                       15,
	"unable to create page token: %s":                                5,
	"unable to decode group: %s":                                     46,
	"unable to decode user: %s":                                      60,
	"unable to encrypt confirmation: %s":                             54,
	"unable to encrypt reset password struct: %s":                    57,
	"unable to find group named %s":                                  49,
	"unable to find group with id %s":                                48,
	"unable to find group with id '%s'":                              52,
	"unable to find user":                                            62,
	"unable to find user with given id":                              66,
	"unable to find user with id %s":                                 61,
	"unable to hash given password":                                  30,
	"unable to json marshal confirmation: %s":                        53,
	"unable to json marshal reset password struct: %s":               56,
	"unable to marshal token to json: %s":                            18,
	"unable to merge groups":                                         16,
	"unable to merge users":                                          34,
	"unable to query groups: %s":                                     45,
	"unable to query members":                                        9,
	"unable to query users: %s":                                      59,
	"unable to remove user from group %s":                            36,
	"unable to save user":                                            39,
	"unable to send reset password mail":                             40,
}

var deIndex = []uint32{ // 68 elements
	// Entry 0 - 1F
	0x00000000, 0x00000020, 0x00000089, 0x000000b0,
	0x000000ce, 0x00000188, 0x000001b7, 0x000001ea,
	0x00000228, 0x00000248, 0x00000272, 0x000002a1,
	0x000002c2, 0x000002e5, 0x0000030c, 0x00000337,
	0x00000365, 0x00000393, 0x000003b9, 0x000003e4,
	0x0000041d, 0x00000468, 0x0000049b, 0x000004e1,
	0x00000506, 0x0000051e, 0x0000053f, 0x00000578,
	0x000005c7, 0x000005e2, 0x00000607, 0x0000063d,
	// Entry 20 - 3F
	0x00000671, 0x000006a9, 0x0000071f, 0x0000074e,
	0x00000779, 0x000007a8, 0x000007e9, 0x00000808,
	0x0000082f, 0x00000860, 0x00000875, 0x00000887,
	0x000008b0, 0x000008dd, 0x0000090b, 0x00000937,
	0x0000094b, 0x0000097c, 0x000009ad, 0x000009cb,
	0x000009ec, 0x00000a1f, 0x00000a53, 0x00000a8a,
	0x00000aa6, 0x00000ae3, 0x00000b23, 0x00000b51,
	0x00000b80, 0x00000baf, 0x00000be4, 0x00000c0a,
	// Entry 40 - 5F
	0x00000c29, 0x00000c4d, 0x00000c64, 0x00000c9f,
} // Size: 296 bytes

const deData string = "" + // Size: 3231 bytes
	"\x02%[1]s: Mail-Adresse bestätigen\x02Hallo %[1]s! Bitte bestätige deine" +
	" Mail-Adresse, indem du auf den folgenden Link klickst. Danke!\x0a%[2]s " +
	"\x02Fehler beim Versenden des Mails: %[1]s\x02%[1]s: Passwort zurücksetz" +
	"en\x02Hallo %[1]s! Um dein Passwort zurückzusetzen, klicke den folgenden" +
	" Link: \x0a%[2]s\x0a\x0aFalls du das zurücksetzen des Passworts nicht an" +
	"gefordert hast, bitte ignoriere diese Nachricht. Danke\x02Page Token kon" +
	"nte nicht erstellt werden: %[1]s\x02Gruppe mit ID '%[1]s' konnte nicht g" +
	"efunden werden\x02Name der Gruppe sollte mindestens eine Länge von 3 auf" +
	"weisen\x02Fehler beim Zählen der Gruppen\x02Mitglieder konnten nicht abg" +
	"efragt werden\x02Nur %[1]v der %[2]v Mitglieder wurden gefunden\x02Fehle" +
	"r beim Agfragen der Gruppen\x02Fehler beim Abfragen des Mitglieds\x02Nic" +
	"ht berechtigt, Gruppen zu erstellen\x02Nicht berechtigt, Gruppen zu aktu" +
	"alisieren\x02Feldmaske konnte nicht erstellt werden: %[1]s\x02Gruppen ko" +
	"nnten nicht zusammengeführt werden\x02Nicht berechtigt, Gruppen zu lösch" +
	"en\x02Token kann nicht umgewandelt werden: %[1]s\x02Ungültiger Page Toke" +
	"n, Umwandlung nicht möglich: %[1]s\x02Filter %[1]s stimmt nicht mit dem " +
	"Filter %[2]s aus dem Page Token überein\x02Benutzer mit id %[1]s konnte " +
	"nicht gefunden werden\x02Ungüliger Benutzername, nur Kleinbuchstaben und" +
	" Nummern sind erlaubt\x02Sprache konnte nicht bestimmt werden\x02Ungülti" +
	"ge Mail Adresse\x02Fehler beim Zählen der Benutzer\x02Das Passwort muss " +
	"mindestens eine Länge von 7 aufweisen\x02Rollen können nicht direkt Benu" +
	"tzern zugewiesen werden, verwende Gruppen dazu\x02Mail Adresse nicht geg" +
	"eben\x02Bestätigt darf nicht gesetzt werden\x02Es konnte kein Hash für d" +
	"as Passwort erstellt werden\x02Keine Berechtigung um andere Benutzer zu " +
	"bearbeiten\x02Rollen können nicht direkt Benutzern zugeordnet werden\x02" +
	"Passwort kann nicht mit der UpdateUser Funktion aktualisiert werden, ver" +
	"wende die ChangePassword Funktion stattdessen\x02Benutzer können nicht z" +
	"usammengeführt werden\x02Keine Berechtigung um Benutzer zu löschen\x02Be" +
	"nutzer kann nicht von Gruppe entfernt werden\x02Keine Berechtigungen um " +
	"das Passwort anderer Benutzer zu ändern\x02Passwort stimmt nicht überein" +
	"\x02Benutzer kann nicht gespeichert werden\x02Passwort Reset Mail konnte" +
	" nicht versandt werden\x02Kein Token angegeben\x02ungültiger Token\x02di" +
	"e Anfrage wurde vom Client abgebrochen\x02Gruppen können nicht gezählt w" +
	"erden: %[1]s\x02Gruppen können nicht abgefragt werden: %[1]s\x02Gruppe k" +
	"onnte nicht decodiert werden: %[1]s\x02ungültige ID %[1]s\x02Gruppe mit " +
	"id %[1]s konnte nicht gefunden werden\x02Gruppe namens %[1]s konnte nich" +
	"t gefunden werden\x02Ungültige Gruppen-ID '%[1]s'\x02Fehler beim Speiche" +
	"rn der Gruppe\x02Gruppe mit ID '%[1]s' konnte nicht gefunden werden\x02B" +
	"estätigung konnte nicht umgewandelt werden: %[1]s\x02Bestätigung konnte " +
	"nicht verschlüsselt werden: %[1]s\x02Token stimmt nicht überein\x02Passw" +
	"ort Reset Objekt konnte nicht umgewandelt werden: %[1]s\x02Passwort Rese" +
	"t Objekt konnte nicht verschlüsselt werden: %[1]s\x02Benutzer konnten ni" +
	"cht gezählt werden: %[1]s\x02Benutzer konnten nicht abgefragt werden: %[" +
	"1]s\x02Benutzer konnten nicht dekodiert werden: %[1]s\x02Benutzer mit ID" +
	" '%[1]s' konnte nicht gefunden werden\x02Benutzer konnte nicht gefunden " +
	"werden\x02Ungültige Benutzer ID '%[1]s'\x02Fehler beim Speichern des Ben" +
	"utzers\x02Ungültige Benutzer ID\x02Benutzer mit der gegebenen ID konnte " +
	"nicht gefunden werden"

var enIndex = []uint32{ // 68 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001c, 0x00000075, 0x00000095,
	0x000000ab, 0x00000141, 0x00000164, 0x00000187,
	0x000001b7, 0x000001d3, 0x000001eb, 0x0000021a,
	0x00000238, 0x00000254, 0x00000271, 0x0000028e,
	0x000002ba, 0x000002d1, 0x000002ee, 0x00000315,
	0x00000352, 0x00000395, 0x000003b7, 0x000003f8,
	0x00000417, 0x0000042c, 0x00000447, 0x00000471,
	0x000004b0, 0x000004c5, 0x000004e2, 0x00000500,
	// Entry 20 - 3F
	0x00000520, 0x0000054b, 0x000005a0, 0x000005b6,
	0x000005d1, 0x000005f8, 0x00000627, 0x00000639,
	0x0000064d, 0x00000670, 0x0000067f, 0x0000068d,
	0x000006b4, 0x000006d2, 0x000006f0, 0x0000070e,
	0x00000721, 0x00000744, 0x00000765, 0x0000077e,
	0x00000797, 0x000007bc, 0x000007e7, 0x0000080d,
	0x0000081c, 0x00000850, 0x0000087f, 0x0000089c,
	0x000008b9, 0x000008d6, 0x000008f8, 0x0000090c,
	// Entry 40 - 5F
	0x00000924, 0x0000093c, 0x0000094c, 0x0000096e,
} // Size: 296 bytes

const enData string = "" + // Size: 2414 bytes
	"\x02%[1]s: confirm mail address\x02Hi %[1]s! Please confirm your mail ad" +
	"dress by clicking the following link. Thanks!\x0a%[2]s\x02error while se" +
	"nding mail: %[1]s\x02%[1]s: password reset\x02Hi %[1]s! To reset your pa" +
	"ssword, click the following link: \x0a%[2]s\x0a\x0aIf you did not reques" +
	"t to reset your password, please ignore this message. Thanks\x02unable t" +
	"o create page token: %[1]s\x02could not find group with id %[1]s\x02grou" +
	"p name needs to have a length of at least 3\x02error while counting grou" +
	"ps\x02unable to query members\x02only %[1]v of %[2]v given memberIds wer" +
	"e found\x02error while looking up groups\x02error while querying member" +
	"\x02not allowed to create groups\x02not allowed to update groups\x02unab" +
	"le to create generate field mask: %[1]s\x02unable to merge groups\x02not" +
	" allowed to delete groups\x02unable to marshal token to json: %[1]s\x02i" +
	"nvalid page token, unable to unmarshal to page token: %[1]s\x02mismatch " +
	"between given filter %[1]s and filter in page token %[2]s\x02could not f" +
	"ind user with id %[1]s\x02invalid username, only lowercase letters and n" +
	"umbers are allowed\x02could not parse given language\x02invalid mail add" +
	"ress\x02error while counting users\x02password must have a length of at " +
	"least 7\x02roles cannot be assigned to users directly, use groups instea" +
	"d\x02mail address not set\x02not allowed to set confirmed\x02unable to h" +
	"ash given password\x02not allowed to edit other users\x02roles cannot be" +
	" assigned to users directly\x02password cannot be changed using the Upda" +
	"teUser function, use ChangePassword instead\x02unable to merge users\x02" +
	"not allowed to delete user\x02unable to remove user from group %[1]s\x02" +
	"not allowed to change password for other users\x02password mismatch\x02u" +
	"nable to save user\x02unable to send reset password mail\x02no token giv" +
	"en\x02invalid token\x02the request was canceled by the client\x02unable " +
	"to count groups: %[1]s\x02unable to query groups: %[1]s\x02unable to dec" +
	"ode group: %[1]s\x02invalid id '%[1]s'\x02unable to find group with id %" +
	"[1]s\x02unable to find group named %[1]s\x02invalid group id '%[1]s'\x02" +
	"error while saving group\x02unable to find group with id '%[1]s'\x02unab" +
	"le to json marshal confirmation: %[1]s\x02unable to encrypt confirmation" +
	": %[1]s\x02token mismatch\x02unable to json marshal reset password struc" +
	"t: %[1]s\x02unable to encrypt reset password struct: %[1]s\x02unable to " +
	"count users: %[1]s\x02unable to query users: %[1]s\x02unable to decode u" +
	"ser: %[1]s\x02unable to find user with id %[1]s\x02unable to find user" +
	"\x02invalid user id '%[1]s'\x02error while saving user\x02invalid user i" +
	"d\x02unable to find user with given id"

	// Total table size 6237 bytes (6KiB); checksum: 9B6A0EE9
